DOP-1956 Deploy of multiple versions of docs-kafka-connector from slack did not work properly
mongodb/snooty-workerpool-stitchapp pull request #5
Opened 2021-03-18 15:34 UTC by GuruPKK

Following are my observations while investigating this issue

- I see there are 3 conditional logic in the deployRepoStart webhook
    - With publishOriginalBranchName and aliases Present
    - Without aliases 
    - Without publishOriginalBranchName
- I see conditional blocks are not terminated (with a else), which executes the other conditions also if met.. 
    - For ex: if the repo has both publishOriginalBranchName and aliases, we will start the build and we will still execute the last block as there is no else part to it. 
- This results in multiple jobs queued up for the same branch
- Whenever there is repo without aliases, i see a return right after we queue the job which results in only some branches are built.

2021-03-18 16:36 UTC, madelinezec requested changes

2021-03-18 16:36 UTC, madelinezec commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    else {
Hi @GuruPKK this is a great first pass!

Unfortunately, we need the aliases to be queued up as well. 

If we put this line in an else, then the aliases don't get queued up.

2021-03-18 17:30 UTC, GuruPKK commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    else {
Ok Updated it

2021-03-19 15:55 UTC, madelinezec commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    if (aliases === null) {
Thanks for this change. I'm thinking one way we could make the code a little more readable is here:

```suggestion
        //non-aliased branch
    if (aliases === null) {
      //if this is stablebranch, we want autobuilder to know this is unaliased branch and therefore can reindex for search
      const newPayload = context.functions.execute("createNewPayload", "productionDeploy", repoOwner, repoName, branchName,  hashOption, false, null)
      context.functions.execute("addJobToQueue", newPayload, jobTitle, jobUserName, jobUserEmail, coll_name);
    }
    //aliased branch
    else {
      // we use the primary alias for indexing search, not the original branch name (ie 'master'), for aliased repos 
      if (publishOriginalBranchName && aliases) {
        const newPayload = context.functions.execute("createNewPayload", "productionDeploy", repoOwner, repoName, branchName,  hashOption, true, null)
        context.functions.execute("addJobToQueue", newPayload, jobTitle, jobUserName, jobUserEmail, coll_name);  
      }
      aliases.forEach(function(alias, index) {
        const primaryAlias = (index === 0); 
        const newPayload = context.functions.execute("createNewPayload", "productionDeploy", repoOwner, repoName, branchName, hashOption, true, alias, primaryAlias)
        context.functions.execute("addJobToQueue", newPayload, jobTitle, jobUserName, jobUserEmail, coll_name); 
      })
    }
```

Does that seem reasonable to you?

2021-03-19 17:56 UTC, GuruPKK commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    if (aliases === null) {
Yeah this looks good

2021-03-22 15:34 UTC, madelinezec commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    if (aliases === null) {
Could we please include the comment,     //non-aliased branch, on line 76 (like in my example) and also move the comment,  //if this is stablebranch, we want autobuilder to know this is unaliased branch and therefore can reindex for search, below the if on line 78

2021-03-22 15:44 UTC, GuruPKK commented on services/deployRepoOptions/incoming_webhooks/deployRepoStart/source.js
> +    if (aliases === null) {
Done

2021-03-22 16:08 UTC, madelinezec approved these changes
LGTM

2021-03-22 16:42 UTC, merged